version: '3.7'
services:
  cinema-web:
    image: nginx:latest
    container_name: cinema-web
    volumes:
      - .:/usr/share/nginx/html/api
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf
    ports:
      - 10580:80
      - 10543:443
    networks:
      - cinema-api-network
    links:
      - php
  php:
    image: reynier3mil/centos-php-fpm-msphpsql:latest
    container_name: php
    volumes:
      - .:/usr/share/nginx/html/api
      - ./logs/php-fpm:/var/log/php-fpm
      - ./config/php-fpm/php.ini:/etc/php.ini
      - ./config/php-fpm/php-fpm.conf:/etc/php-fpm.conf
      - ./config/php-fpm/www.conf:/etc/php-fpm.d/www.conf
      - ./config/php-fpm/10-opcache.ini:/etc/php.d/10-opcache.ini
      - ./config/php-fpm/16-xdebug.ini:/etc/php.d/15-xdebug.ini
    ports:
      - 9050:9050
    networks:
      - cinema-api-network
    links:
      - mssql
      - memcached
      - neo4j
      - mongo
    working_dir: /usr/share/nginx/html/api
  mssql:
    image: reynier3mil/centos-mssql-full:latest
    container_name: mssql
    volumes:
      - ./data/mssql/backups:/tmp/backups
    ports:
      - 1433:1433
    networks:
      - cinema-api-network
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ms3CjP{R?1^A
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - 11211:11211
    networks:
      - cinema-api-network
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - ./data/neo4j:/data
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - cinema-api-network
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./data/mongo:/etc/mongo
    ports:
      - 27017:27017
    networks:
      - cinema-api-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME="root"
      - MONGO_INITDB_ROOT_PASSWORD="ms3CjP{R?1^A"
networks:
  cinema-api-network:
    driver: bridge
    name: cinema-api-network